

###
GET http://localhost:3000/login

# &page=1&count=3
###
GET http://localhost:3000/qa/questions?product_id=188

# '/qa/questions': addQuestion.jsx
###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "a",
    "password": "1"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "a",
    "password": "2"
}